Expense Manager Using Dapper/Controllers/ManageExpenseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using Expense_Manager_Using_Dapper.Models;

namespace Expense_Manager_Using_Dapper.Controllers
{
   
    public class ManageExpenseController : Controller
    {
        SqlConnection con = new SqlConnection("Data Source = DESKTOP-9SVH54V\\SQLEXPRESS;Initial Catalog=ExpenseManagerDB;Integrated Security=true");
        // GET: ManageExpense
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewExpenses()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login","User");
            }
            var paramters = new DynamicParameters();
            paramters.Add("@userid", (Int32)Session["UserId"]);
            IEnumerable<ExpensesModel> Expenselist = con.Query<ExpensesModel>("getexpensesforuser", param: paramters, commandType: CommandType.StoredProcedure);
            return View(Expenselist);
        }

        public ActionResult AddExpense()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddExpense(ExpensesModel expense)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            var prameters = new DynamicParameters();

            prameters.Add("@userId", (Int32)Session["UserId"]);
            prameters.Add("@Amount", expense.Amount);
            prameters.Add("@Purpose", expense.Purpose);
            prameters.Add("@expenseType", expense.expenseType);

            int num = con.Execute("sp_CreateExpense", param: prameters, commandType: System.Data.CommandType.StoredProcedure);

            if (num > 0) { 
                
                return RedirectToAction("ViewExpenses");
            
            }
                return View();
        }

        public ExpensesModel ExpenseById(int id)
        {

            var parameters = new DynamicParameters();
            parameters.Add("@id", id);

            ExpensesModel expense = con.QuerySingleOrDefault<ExpensesModel>("sp_ExpenseById", param: parameters, commandType: System.Data.CommandType.StoredProcedure);
            return expense;
        }

        public ActionResult DeleteExpense(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            return View(ExpenseById(id));
        }

        [ActionName("DeleteExpense")]
        [HttpPost]
        public ActionResult DeleteExpenseConfirm(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            var prams = new DynamicParameters();
            prams.Add("@id", id);

            int num = con.Execute("sp_deleteExpenseById", param: prams, commandType: System.Data.CommandType.StoredProcedure);

            if(num > 0)
            {
                return RedirectToAction("ViewExpenses");
            }
            return View();
        }

        public ActionResult UpdateExpense(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View(ExpenseById(id));
        }

        [ActionName("UpdateExpense")]
        [HttpPost]
        public ActionResult UpdateExpenseCofirm(ExpensesModel expense)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            var parameters = new DynamicParameters();
            parameters.Add("@expenseId", expense.expenseId);
            parameters.Add("@Amount", expense.Amount);
            parameters.Add("@Purpose", expense.Purpose);
            parameters.Add("@expenseType", expense.expenseType);
            int num = con.Execute("sp_updateExpense", param:parameters, commandType:System.Data.CommandType.StoredProcedure);
            if(num > 0)
            {
                return RedirectToAction("ViewExpenses");
            }
            else
            {
                return View();
            }

        }

        public ActionResult ViewDetails(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View(ExpenseById(id));
        }

        public ActionResult ViewAllIncomes()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            var paramters = new DynamicParameters();
            paramters.Add("@userid", (Int32)Session["UserId"]);
            IEnumerable<IncomeModel> Incomelist = con.Query<IncomeModel>("getincomesforuser", param: paramters, commandType: CommandType.StoredProcedure);
            return View(Incomelist);
        }

        public ActionResult AddIncome()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddIncome(IncomeModel model)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            var parameters = new DynamicParameters();
            parameters.Add("@userId", (Int32)Session["UserId"]);
            parameters.Add("@Amount", model.Amount);
            parameters.Add("@Source", model.Source);
            parameters.Add("@IncomeType",model.IncomeType);

            int num = con.Execute("sp_CreateIncome", param: parameters, commandType: System.Data.CommandType.StoredProcedure);
            if(num > 0)
            {
                return RedirectToAction("ViewAllIncomes");
            }
            else
            {
                return View();
            }
        }

        public IncomeModel IncomeById(int id)
        {

            var parameters = new DynamicParameters();
            parameters.Add("@id", id);
            IncomeModel income = con.QuerySingleOrDefault<IncomeModel>("sp_IncomeById", param:parameters,commandType:System.Data.CommandType.StoredProcedure);
            return income;
        }

        public ActionResult UpdateIncome(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View(IncomeById(id));
        }

        [HttpPost]
        public ActionResult UpdateIncome(IncomeModel model)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            var parameters = new DynamicParameters();
            parameters.Add("@incomeId", model.incomeId);
            parameters.Add("@Amount", model.Amount);
            parameters.Add("@Source", model.Source);
            parameters.Add("@IncomeType", model.IncomeType);
            int num = con.Execute("sp_UpdateIncome",param:parameters,commandType:System.Data.CommandType.StoredProcedure);
            if(num > 0)
            {
                return RedirectToAction("ViewAllIncomes");
            }
            else
            {
                return View();
            }
        }

        public ActionResult DeleteIncome(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View(IncomeById(id));
        }

        [ActionName("DeleteIncome")]
        [HttpPost]
        public ActionResult DeleteIncomeConfirm(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            var parameters = new DynamicParameters();
            parameters.Add("@id",id);
            int num = con.Execute("sp_DeleteIncomeById",param:parameters,commandType:System.Data.CommandType.StoredProcedure);
            if(num > 0)
            {
                return RedirectToAction("ViewAllIncomes");
            }
            else
            {
                return View();
            }
        }
       
        public ActionResult IncomeDetails(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View(IncomeById(id));
        }


    }

}

Expense Manager Using Dapper/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Dapper;
using Expense_Manager_Using_Dapper.Models;
using Microsoft.Ajax.Utilities;

namespace Expense_Manager_Using_Dapper.Controllers
{
    public class UserController : Controller
    {
        SqlConnection con = new SqlConnection("Data Source = DESKTOP-9SVH54V\\SQLEXPRESS;Initial Catalog=ExpenseManagerDB;Integrated Security=true");
        // GET: User
        public ActionResult Index()
        {

            return RedirectToAction("Login");
        }

        public ActionResult UsersList()
        {
            //con.Query<UserModel>("sp_CreateUser", param: prameters, commandType: CommandType.StoredProcedure);
            return View();
        }

        public UserModel GetUserByEmail(UserModel user)
        {
            var prameters = new DynamicParameters();
            prameters.Add("@email", user.Email);
            UserModel userdata = con.QuerySingleOrDefault<UserModel>("sp_getUserByEmail", param: prameters, commandType: CommandType.StoredProcedure);
            return userdata;
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserModel user)
        {
            UserModel userdata = GetUserByEmail(user);

            if (userdata != null)
            {
                ViewBag.Error = "User Already Exist";
                return RedirectToAction("Register");
            }
            
            var prameters = new DynamicParameters();
            prameters.Add("@username", user.username);
            prameters.Add("@Email", user.Email);
            prameters.Add("@userpassword", user.userpassword);
            prameters.Add("@Mobile", user.Mobile);
            int num = con.Execute("sp_CreateUser", param: prameters, commandType: CommandType.StoredProcedure);
            if(num > 0)
            {
                ViewBag.Error = "User Created Successfully";
                return RedirectToAction("Register");
            }
            else
            {
                ViewBag.Error = "User is not created ";
                return RedirectToAction("Register");
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        [ActionName("Login")]
        [HttpPost]
        public ActionResult LoginConfirm(UserModel user)
        {
            var prameters = new DynamicParameters();
            prameters.Add("@Email", user.Email);
            UserModel userdata = con.QuerySingle<UserModel>("sp_getUserByEmail", param: prameters, commandType: CommandType.StoredProcedure);
            if (userdata != null)
            {
                if (user.userpassword == userdata.userpassword)
                {
                    Session["Email"] = userdata.Email;
                    Session["UserId"] = userdata.Id;
                    Session["UserName"] = userdata.username;
                    return RedirectToAction("Dashboard");
                }
                else
                {
                    ViewBag.Error = "Invalid Email or Password";
                    return RedirectToAction("Login");
                }
            }
            else
            {
                ViewBag.Error = "User Does not Exist";
                return RedirectToAction("Login");
            }
            
            
        }

        public List<ExpensesModel> getAllExpensesForUser()
        {
            var paramters = new DynamicParameters();
            paramters.Add("@userid", (Int32)Session["UserId"] );
            IEnumerable<ExpensesModel> Expenselist = con.Query<ExpensesModel>("getexpensesforuser",param:paramters, commandType: CommandType.StoredProcedure);
            return Expenselist.ToList();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }


        public List<IncomeModel> getAllIncomesForUser()
        {
            var paramters = new DynamicParameters();
            paramters.Add("@userid", (Int32)Session["UserId"]);
            IEnumerable<IncomeModel> Incomelist = con.Query<IncomeModel>("getincomesforuser",param:paramters, commandType: CommandType.StoredProcedure);
            return Incomelist.ToList();
        }

        public AllExpenseTotal getTotalExpense()
        {
            var paramters = new DynamicParameters();
            paramters.Add("id", (Int32)Session["UserId"]);
            AllExpenseTotal total = con.QuerySingle<AllExpenseTotal>("sp_getTotalExpense", param: paramters, commandType: CommandType.StoredProcedure);
            return total;
        }
        public AllIncomesTotal getTotalIncomes()
        {
            var paramters = new DynamicParameters();
            paramters.Add("id", (Int32)Session["UserId"]);
            AllIncomesTotal total = con.QuerySingle<AllIncomesTotal>("sp_getTotalIncome", param: paramters, commandType: CommandType.StoredProcedure);
            return total;
        }

        public ActionResult Dashboard()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                AllExpenseAndIncomes all = new AllExpenseAndIncomes();

                List<ExpensesModel> expenses = getAllExpensesForUser();
                List<IncomeModel> income = getAllIncomesForUser();
                AllIncomesTotal TotalIncome = getTotalIncomes();
                AllExpenseTotal totalExpense = getTotalExpense();

                all.totalIncome = TotalIncome;
                all.totalExpense = totalExpense;
                all.Expenses = expenses;
                all.incomes = income;

                return View(all);
            }
        }
    }
}

Expense Manager Using Dapper/Views/User/Dashboard.cshtml
@model Expense_Manager_Using_Dapper.Models.AllExpenseAndIncomes
@{
    ViewBag.Title = "Dashboard";
}

<div class="container mt-5">
    <div class="row">
        <!-- Sidebar -->
        <div class="col-md-3 text-light p-3">
            <h2 class="text-light">Expense Manager</h2>
            <ul class="nav flex-column">
                <li class="nav-item">
                    @Html.ActionLink("Add Expense", "AddExpense", "ManageExpense", null, htmlAttributes: new { @class = "nav-link text-light" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Manage Expenses", "ViewExpenses", "ManageExpense", null, htmlAttributes: new { @class = "nav-link text-light" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Add Income", "AddIncome", "ManageExpense", null, htmlAttributes: new { @class = "nav-link text-light" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Manage Incomes", "ViewAllIncomes", "ManageExpense", null, htmlAttributes: new { @class = "nav-link text-light" })
                </li>
            </ul>
            <div class="mt-3 text-light">Balance: @(Model.totalIncome.TotalIncome - Model.totalExpense.TotalExpense)</div>
        </div>

        <!-- Main Content -->
        <div class="col-md-9">
            <h2 class="text-primary">Dashboard</h2>

            <!-- Recent Expenses -->
            <div class="card mt-4">
                <div class="card-header bg-danger text-light">
                    Recent Expenses
                </div>
                <ul class="list-group list-group-flush">
                    <!-- Loop through recent expenses and display -->
                    @Html.Partial("~/Views/Shared/_Dashboard_Expenses.cshtml", Model.Expenses)
                </ul>
            </div>

            <!-- Recent Incomes -->
            <div class="card mt-4">
                <div class="card-header bg-success text-light">
                    Recent Incomes
                </div>
                <ul class="list-group list-group-flush">
                    <!-- Loop through recent incomes and display -->
                    @Html.Partial("~/Views/Shared/_Dashboard_Incomes.cshtml", Model.incomes)
                </ul>
            </div>
        </div>
    </div>
</div>

Expense Manager Using Dapper/Views/User/Login.cshtml
@model Expense_Manager_Using_Dapper.Models.UserModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userpassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userpassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userpassword, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (ViewBag.Error != null)
{
    @ViewBag.Error
}

<div>
    @Html.ActionLink("Register Here", "Register")
</div>

Expense Manager Using Dapper/Views/User/Register.cshtml
@model Expense_Manager_Using_Dapper.Models.UserModel

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userpassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userpassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userpassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (ViewBag.Error != null)
{
    @ViewBag.Error
}
<div>
    @Html.ActionLink("lOGIN here", "Login")
</div>